version: "3"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  back:
    image: back
    build: ./back
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - back-data:/app/data

  front:
    image: front
    ports:
      - "127.0.0.1:8080:8080"
    build: ./front
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@local.com"
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
  back-data:
  pgadmin: